server:
  port: 8081
  servlet:
    context-path: /
  ssl:
    key-store: classpath:server.keystore
    key-alias: tomcat
    enabled: true
    key-store-password: 123456
    key-store-type: JKS

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      # wrjweb数据库
      master:
        url: jdbc:mysql://localhost:3306/db_sperms?useSSL=false&characterEncoding=UTF-8
        username: sperms
        password: Sperms_123
      # 使用druid数据源
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #慢sql记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mqtt:
      username: smart_api
      password: gz!@uuc
      #MQTT-服务器连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613，tcp://192.168.2.133:61613
      url: tcp://127.0.0.1:1883
      #MQTT-连接服务器默认客户端ID
      client:
        id: bridge_aws
      #MQTT-默认的消息推送主题，实际可在调用接口时指定
      default:
        topic: topic1
      #连接超时
      completionTimeout: 3000
      #对接协议订阅主题前缀
      api:
        topic_prefix:
          smart_android: /machine_android/
          smart_web: /machine_web/

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/

  mvc:
    throw-exception-if-no-handler-found: true

#mybaits配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.smart.sperms.dao.model

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    # 指定包设置debug级别
    com.smart.sperms.dao: debug
    #mongodb debug设置
    org.springframework.data.mongodb.core: debug

# 加密算法配置
encrypt:
    xxtea:
        ## key_smart: 25fd36gfegl
        key_smart: smart_encrypt_test

# 文件存储路径
file_store:
  image_path: /opt/file_store/images

#management:
#  endpoint:
#    health:
#      show-details: always